export type DefaultPackingListItem = {
  category: string;
  label: string;
};

export const DEFAULT_PACKING_LIST_ITEMS: DefaultPackingListItem[] = [
  { category: 'Basics', label: 'undies' },
  { category: 'Basics', label: 'socks' },
  { category: 'Basics', label: 'bras' },
  { category: 'Basics', label: 'sleepwear' },
  { category: 'Basics', label: 'slippers for hotel' },
  { category: 'Casual', label: 'T-shirts' },
  { category: 'Casual', label: 'shorts' },
  { category: 'Casual', label: 'Jeans' },
  { category: 'Casual', label: 'swimsuits' },
  { category: 'Casual', label: 'sandals' },
  { category: 'Casual', label: 'sneakers' },
  { category: 'Casual', label: 'fleece/cardigan/sweater' },
  { category: 'Dressy', label: 'Dresses' },
  { category: 'Dressy', label: 'skirts' },
  { category: 'Dressy', label: 'dress shoes/sandals' },
  { category: 'Dressy', label: 'formal night outfit' },
  { category: 'Outerwear & Accessories', label: 'rain jackets' },
  { category: 'Outerwear & Accessories', label: 'warm jackets' },
  { category: 'Outerwear & Accessories', label: 'fleece' },
  { category: 'Outerwear & Accessories', label: 'scarves' },
  { category: 'Outerwear & Accessories', label: 'sun hats/warm hats' },
  { category: 'Outerwear & Accessories', label: 'gloves' },
  { category: 'Outerwear & Accessories', label: 'jewelry' },
  { category: 'Outerwear & Accessories', label: 'sunglasses' },
  { category: 'Outerwear & Accessories', label: 'goggles' },
  { category: 'evening bag', label: 'make up removal wipe' },
  { category: 'evening bag', label: 'cotton balls/Qtips' },
  { category: 'evening bag', label: 'face moisturizer (pm)' },
  { category: 'evening bag', label: 'toothbrush' },
  { category: 'evening bag', label: 'toothpaste' },
  { category: 'evening bag', label: 'toothbrush charger' },
  { category: 'evening bag', label: 'floss' },
  { category: 'evening bag', label: 'glasses' },
  { category: 'evening bag', label: 'rubber band' },
  { category: 'evening bag', label: 'contact lens case' },
  { category: 'evening bag', label: 'extra pair of contacts' },
  { category: 'evening bag', label: 'hair claws (small/big)' },
  { category: 'evening bag', label: 'tweezers' },
  { category: 'evening bag', label: 'nail care supplies' },
  { category: 'morning bag', label: 'eye shadow/pencil' },
  { category: 'morning bag', label: 'lipsticks' },
  { category: 'morning bag', label: 'comb/pick' },
  { category: 'morning bag', label: 'shaving supplies' },
  { category: 'morning bag', label: 'sunscreen' },
  { category: 'morning bag', label: 'insect repellent' },
  { category: 'morning bag', label: 'face moisturizer (am)' },
  { category: 'morning bag', label: 'foundation' },
  { category: 'morning bag', label: 'hand lotion' },
  { category: 'morning bag', label: 'contact lens cleaner' },
  { category: 'morning bag', label: 'shampoo/conditioner' },
  { category: 'morning bag', label: 'shower caps' },
  { category: 'morning bag', label: 'soap' },
  { category: 'medicine bag', label: 'zicam' },
  { category: 'medicine bag', label: 'Dramamine/Sea band' },
  { category: 'medicine bag', label: 'Huang Lian Su' },
  { category: 'medicine bag', label: 'Vitamin B' },
  { category: 'medicine bag', label: 'Vitamin D' },
  { category: 'medicine bag', label: 'Advil' },
  { category: 'medicine bag', label: 'Tylanol' },
  { category: 'medicine bag', label: 'Claritin' },
  { category: 'medicine bag', label: 'aloe for sunburn' },
  { category: 'medicine bag', label: 'band aid' },
  { category: 'medicine bag', label: 'neosporene' },
  { category: 'Travel Aids', label: 'reading material' },
  { category: 'Travel Aids', label: 'gums' },
  { category: 'Travel Aids', label: 'snacks/granola bars' },
  { category: 'Travel Aids', label: 'sleep masks' },
  { category: 'Travel Aids', label: 'earplugs' },
  { category: 'Travel Aids', label: 'face masks' },
  { category: 'Travel Aids', label: 'travel pillow' },
  { category: 'Travel Aids', label: 'water bottle' },
  { category: 'Travel info', label: 'passports' },
  { category: 'Travel info', label: "driver's license" },
  { category: 'Travel info', label: 'itinerary' },
  { category: 'Travel info', label: 'maps/directions' },
  { category: 'Travel info', label: 'travel confirmations' },
  { category: 'Travel info', label: 'copies of credit cards' },
  { category: 'Travel info', label: 'copies of passports' },
  { category: 'Travel info', label: 'medical insurance card' },
  { category: 'Electronics Pouch', label: 'cell phone' },
  { category: 'Electronics Pouch', label: 'cell phone charger' },
  { category: 'Electronics Pouch', label: 'cell phone battery' },
  { category: 'Electronics Pouch', label: 'headphones' },
  { category: 'Electronics Pouch', label: 'extra outlet' },
  { category: 'Electronics Pouch', label: 'adapters' },
  { category: 'Electronics Pouch', label: 'laptop/charger' },
  { category: 'Misc', label: 'umbrella' },
  { category: 'Misc', label: 'pens and markers' },
  { category: 'Misc', label: 'tissues' },
  { category: 'Misc', label: 'wipes' },
  { category: 'Misc', label: 'wood pegs (for drying socks)/clips' },
  { category: 'Misc', label: 'wine opening cork screw' },
  { category: 'Misc', label: 'watch' },
  { category: 'Misc', label: 'tea bags' },
  { category: 'Funds', label: 'wallet' },
  { category: 'Funds', label: 'cash' },
  { category: 'Funds', label: 'credit cards' },
  { category: 'Funds', label: 'ATM cards' },
  { category: 'Bags', label: 'backpack' },
  { category: 'Bags', label: 'purses' },
  { category: 'Bags', label: 'foldable day bag' },
  { category: 'Bags', label: 'plastic bags' },
  { category: 'Bags', label: 'garbage bags' },
  { category: 'Bags', label: 'ziplock bags' },
  { category: 'laundry', label: 'laundry bag for dirty clothes' },
  { category: 'laundry', label: 'laundry detergent strips' },
  { category: 'laundry', label: 'laundry net for delicates' },
];
