DELETE FROM universal_packing_list_items;

INSERT INTO universal_packing_list_items (id, category, label, position)
VALUES
  (uuid_generate_v4(), 'Basics', 'undies', 0),
  (uuid_generate_v4(), 'Basics', 'socks', 1),
  (uuid_generate_v4(), 'Basics', 'bras', 2),
  (uuid_generate_v4(), 'Basics', 'sleepwear', 3),
  (uuid_generate_v4(), 'Basics', 'slippers for hotel', 4),
  (uuid_generate_v4(), 'Casual', 'T-shirts', 5),
  (uuid_generate_v4(), 'Casual', 'shorts', 6),
  (uuid_generate_v4(), 'Casual', 'Jeans', 7),
  (uuid_generate_v4(), 'Casual', 'swimsuits', 8),
  (uuid_generate_v4(), 'Casual', 'sandals', 9),
  (uuid_generate_v4(), 'Casual', 'sneakers', 10),
  (uuid_generate_v4(), 'Casual', 'fleece/cardigan/sweater', 11),
  (uuid_generate_v4(), 'Dressy', 'Dresses', 12),
  (uuid_generate_v4(), 'Dressy', 'skirts', 13),
  (uuid_generate_v4(), 'Dressy', 'dress shoes/sandals', 14),
  (uuid_generate_v4(), 'Dressy', 'formal night outfit', 15),
  (uuid_generate_v4(), 'Outerwear & Accessories', 'rain jackets', 16),
  (uuid_generate_v4(), 'Outerwear & Accessories', 'warm jackets', 17),
  (uuid_generate_v4(), 'Outerwear & Accessories', 'fleece', 18),
  (uuid_generate_v4(), 'Outerwear & Accessories', 'scarves', 19),
  (uuid_generate_v4(), 'Outerwear & Accessories', 'sun hats/warm hats', 20),
  (uuid_generate_v4(), 'Outerwear & Accessories', 'gloves', 21),
  (uuid_generate_v4(), 'Outerwear & Accessories', 'jewelry', 22),
  (uuid_generate_v4(), 'Outerwear & Accessories', 'sunglasses', 23),
  (uuid_generate_v4(), 'Outerwear & Accessories', 'goggles', 24),
  (uuid_generate_v4(), 'evening bag', 'make up removal wipe', 25),
  (uuid_generate_v4(), 'evening bag', 'cotton balls/Qtips', 26),
  (uuid_generate_v4(), 'evening bag', 'face moisturizer (pm)', 27),
  (uuid_generate_v4(), 'evening bag', 'toothbrush', 28),
  (uuid_generate_v4(), 'evening bag', 'toothpaste', 29),
  (uuid_generate_v4(), 'evening bag', 'toothbrush charger', 30),
  (uuid_generate_v4(), 'evening bag', 'floss', 31),
  (uuid_generate_v4(), 'evening bag', 'glasses', 32),
  (uuid_generate_v4(), 'evening bag', 'rubber band', 33),
  (uuid_generate_v4(), 'evening bag', 'contact lens case', 34),
  (uuid_generate_v4(), 'evening bag', 'extra pair of contacts', 35),
  (uuid_generate_v4(), 'evening bag', 'hair claws (small/big)', 36),
  (uuid_generate_v4(), 'evening bag', 'tweezers', 37),
  (uuid_generate_v4(), 'evening bag', 'nail care supplies', 38),
  (uuid_generate_v4(), 'morning bag', 'eye shadow/pencil', 39),
  (uuid_generate_v4(), 'morning bag', 'lipsticks', 40),
  (uuid_generate_v4(), 'morning bag', 'comb/pick', 41),
  (uuid_generate_v4(), 'morning bag', 'shaving supplies', 42),
  (uuid_generate_v4(), 'morning bag', 'sunscreen', 43),
  (uuid_generate_v4(), 'morning bag', 'insect repellent', 44),
  (uuid_generate_v4(), 'morning bag', 'face moisturizer (am)', 45),
  (uuid_generate_v4(), 'morning bag', 'foundation', 46),
  (uuid_generate_v4(), 'morning bag', 'hand lotion', 47),
  (uuid_generate_v4(), 'morning bag', 'contact lens cleaner', 48),
  (uuid_generate_v4(), 'morning bag', 'shampoo/conditioner', 49),
  (uuid_generate_v4(), 'morning bag', 'shower caps', 50),
  (uuid_generate_v4(), 'morning bag', 'soap', 51),
  (uuid_generate_v4(), 'medicine bag', 'zicam', 52),
  (uuid_generate_v4(), 'medicine bag', 'Dramamine/Sea band', 53),
  (uuid_generate_v4(), 'medicine bag', 'Huang Lian Su', 54),
  (uuid_generate_v4(), 'medicine bag', 'Vitamin B', 55),
  (uuid_generate_v4(), 'medicine bag', 'Vitamin D', 56),
  (uuid_generate_v4(), 'medicine bag', 'Advil', 57),
  (uuid_generate_v4(), 'medicine bag', 'Tylanol', 58),
  (uuid_generate_v4(), 'medicine bag', 'Claritin', 59),
  (uuid_generate_v4(), 'medicine bag', 'aloe for sunburn', 60),
  (uuid_generate_v4(), 'medicine bag', 'band aid', 61),
  (uuid_generate_v4(), 'medicine bag', 'neosporene', 62),
  (uuid_generate_v4(), 'Travel Aids', 'reading material', 63),
  (uuid_generate_v4(), 'Travel Aids', 'gums', 64),
  (uuid_generate_v4(), 'Travel Aids', 'snacks/granola bars', 65),
  (uuid_generate_v4(), 'Travel Aids', 'sleep masks', 66),
  (uuid_generate_v4(), 'Travel Aids', 'earplugs', 67),
  (uuid_generate_v4(), 'Travel Aids', 'face masks', 68),
  (uuid_generate_v4(), 'Travel Aids', 'travel pillow', 69),
  (uuid_generate_v4(), 'Travel Aids', 'water bottle', 70),
  (uuid_generate_v4(), 'Travel info', 'passports', 71),
  (uuid_generate_v4(), 'Travel info', 'driver''s license', 72),
  (uuid_generate_v4(), 'Travel info', 'itinerary', 73),
  (uuid_generate_v4(), 'Travel info', 'maps/directions', 74),
  (uuid_generate_v4(), 'Travel info', 'travel confirmations', 75),
  (uuid_generate_v4(), 'Travel info', 'copies of credit cards', 76),
  (uuid_generate_v4(), 'Travel info', 'copies of passports', 77),
  (uuid_generate_v4(), 'Travel info', 'medical insurance card', 78),
  (uuid_generate_v4(), 'Electronics Pouch', 'cell phone', 79),
  (uuid_generate_v4(), 'Electronics Pouch', 'cell phone charger', 80),
  (uuid_generate_v4(), 'Electronics Pouch', 'cell phone battery', 81),
  (uuid_generate_v4(), 'Electronics Pouch', 'headphones', 82),
  (uuid_generate_v4(), 'Electronics Pouch', 'extra outlet', 83),
  (uuid_generate_v4(), 'Electronics Pouch', 'adapters', 84),
  (uuid_generate_v4(), 'Electronics Pouch', 'laptop/charger', 85),
  (uuid_generate_v4(), 'Misc', 'umbrella', 86),
  (uuid_generate_v4(), 'Misc', 'pens and markers', 87),
  (uuid_generate_v4(), 'Misc', 'tissues', 88),
  (uuid_generate_v4(), 'Misc', 'wipes', 89),
  (uuid_generate_v4(), 'Misc', 'wood pegs (for drying socks)/clips', 90),
  (uuid_generate_v4(), 'Misc', 'wine opening cork screw', 91),
  (uuid_generate_v4(), 'Misc', 'watch', 92),
  (uuid_generate_v4(), 'Misc', 'tea bags', 93),
  (uuid_generate_v4(), 'Funds', 'wallet', 94),
  (uuid_generate_v4(), 'Funds', 'cash', 95),
  (uuid_generate_v4(), 'Funds', 'credit cards', 96),
  (uuid_generate_v4(), 'Funds', 'ATM cards', 97),
  (uuid_generate_v4(), 'Bags', 'backpack', 98),
  (uuid_generate_v4(), 'Bags', 'purses', 99),
  (uuid_generate_v4(), 'Bags', 'foldable day bag', 100),
  (uuid_generate_v4(), 'Bags', 'plastic bags', 101),
  (uuid_generate_v4(), 'Bags', 'garbage bags', 102),
  (uuid_generate_v4(), 'Bags', 'ziplock bags', 103),
  (uuid_generate_v4(), 'laundry', 'laundry bag for dirty clothes', 104),
  (uuid_generate_v4(), 'laundry', 'laundry detergent strips', 105),
  (uuid_generate_v4(), 'laundry', 'laundry net for delicates', 106);
